# Generated by Django 5.2.8 on 2025-11-21 19:34

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Direccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_via",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="tipo vía"
                    ),
                ),
                (
                    "nombre_via",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="nombre vía"
                    ),
                ),
                (
                    "numero",
                    models.CharField(blank=True, max_length=20, verbose_name="número"),
                ),
                (
                    "bloque",
                    models.CharField(blank=True, max_length=50, verbose_name="bloque"),
                ),
                (
                    "portal",
                    models.CharField(blank=True, max_length=50, verbose_name="portal"),
                ),
                (
                    "escalera",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="escalera"
                    ),
                ),
                (
                    "planta",
                    models.CharField(blank=True, max_length=20, verbose_name="planta"),
                ),
                (
                    "puerta",
                    models.CharField(blank=True, max_length=20, verbose_name="puerta"),
                ),
                (
                    "entidad_poblacion",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="entidad población"
                    ),
                ),
                (
                    "localidad",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=150,
                        verbose_name="localidad / municipio",
                    ),
                ),
                (
                    "provincia",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=150,
                        verbose_name="provincia",
                    ),
                ),
                (
                    "pais",
                    models.CharField(
                        blank=True, default="ES", max_length=100, verbose_name="país"
                    ),
                ),
                (
                    "codigo_postal",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Código postal inválido",
                                regex="^[0-9A-Z\\-]{3,10}$",
                            )
                        ],
                        verbose_name="código postal",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Teléfono inválido",
                                regex="^\\+?[\\d\\s\\-]{6,20}$",
                            )
                        ],
                        verbose_name="teléfono fijo",
                    ),
                ),
                (
                    "movil",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Teléfono inválido",
                                regex="^\\+?[\\d\\s\\-]{6,20}$",
                            )
                        ],
                        verbose_name="móvil",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="correo electrónico"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Personal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("apellidos", models.CharField(max_length=150)),
                (
                    "sexo",
                    models.CharField(
                        choices=[("H", "Hombre"), ("M", "Mujer"), ("O", "Otro")],
                        max_length=1,
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("DNI", "DNI"),
                            ("NIE", "NIE"),
                            ("PASAPORTE", "Pasaporte"),
                        ],
                        max_length=20,
                    ),
                ),
                ("documento", models.CharField(max_length=20, unique=True)),
                ("cargo", models.CharField(max_length=150)),
                ("habilitado_fitosanitarios", models.BooleanField(default=False)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("TRACTOR", "Tractor"),
                            ("COCHE", "Coche"),
                            ("REMOLQUE", "Remolque"),
                            ("FURGONETA", "Furgoneta"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("matricula", models.CharField(max_length=20, unique=True)),
                ("marca", models.CharField(blank=True, max_length=100, null=True)),
                ("modelo", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Explotacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=250, verbose_name="nombre explotación / comercial"
                    ),
                ),
                (
                    "nif",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=30,
                        verbose_name="NIF explotación",
                    ),
                ),
                (
                    "numero_registro_nacional",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="nº registro nacional"
                    ),
                ),
                (
                    "numero_registro_autonomico",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="nº registro autonómico",
                    ),
                ),
                (
                    "tipo_representacion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PROPIETARIO", "Propietario"),
                            ("REPRESENTANTE", "Representante"),
                        ],
                        max_length=50,
                        verbose_name="tipo de representación",
                    ),
                ),
                (
                    "direccion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="explotaciones",
                        to="gestion.direccion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Explotación",
                "verbose_name_plural": "Explotaciones",
            },
        ),
        migrations.CreateModel(
            name="EquipoAplicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=250, verbose_name="descripción"),
                ),
                (
                    "numero_inscripcion_roma",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Número de inscripción ROMA del equipo (si aplica)",
                        max_length=100,
                        verbose_name="nº inscripción ROMA",
                    ),
                ),
                (
                    "fecha_adquisicion",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha adquisición"
                    ),
                ),
                (
                    "fecha_ultima_inspeccion",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha última inspección"
                    ),
                ),
                (
                    "explotacion",
                    models.ForeignKey(
                        blank=True,
                        help_text="Explotación propietaria o usuaria del equipo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipos",
                        to="gestion.explotacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentoDAT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(db_index=True, max_length=150, unique=True),
                ),
                ("fecha_emision", models.DateField(db_index=True)),
                ("producto", models.CharField(blank=True, max_length=200)),
                (
                    "cantidad",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=14, null=True
                    ),
                ),
                ("unidad", models.CharField(blank=True, max_length=20)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "explotacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_dat",
                        to="gestion.explotacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnalisisLaboratorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(db_index=True)),
                (
                    "material_analizado",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="material analizado"
                    ),
                ),
                (
                    "cultivo",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="cultivo / cosecha"
                    ),
                ),
                (
                    "numero_boletin",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="nº boletín de análisis",
                    ),
                ),
                (
                    "laboratorio",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="laboratorio"
                    ),
                ),
                ("sustancias_activas_detectadas", models.TextField(blank=True)),
                (
                    "explotacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analisis",
                        to="gestion.explotacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Parcela",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "referencia_sigpac",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="referencia SIGPAC",
                    ),
                ),
                (
                    "poligono",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="polígono"
                    ),
                ),
                (
                    "parcela",
                    models.CharField(blank=True, max_length=50, verbose_name="parcela"),
                ),
                (
                    "recinto",
                    models.CharField(blank=True, max_length=50, verbose_name="recinto"),
                ),
                (
                    "uso_sigpac",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="uso SIGPAC"
                    ),
                ),
                (
                    "superficie_sigpac",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="superficie SIGPAC (ha)",
                    ),
                ),
                (
                    "superficie_cultivada",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="superficie cultivada (ha)",
                    ),
                ),
                (
                    "especie",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="especie"
                    ),
                ),
                (
                    "variedad",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="variedad"
                    ),
                ),
                (
                    "secano_regadio",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="secano/regadío"
                    ),
                ),
                (
                    "aire_protegido",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="aire libre / protegido"
                    ),
                ),
                (
                    "explotacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parcelas",
                        to="gestion.explotacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=250, verbose_name="nombre / razón social"
                    ),
                ),
                (
                    "nif",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=30,
                        verbose_name="DNI/NIE/NIF",
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        blank=True,
                        choices=[("H", "Hombre"), ("M", "Mujer"), ("O", "Otro")],
                        max_length=1,
                        verbose_name="sexo",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Teléfono inválido",
                                regex="^\\+?[\\d\\s\\-]{6,20}$",
                            )
                        ],
                        verbose_name="teléfono",
                    ),
                ),
                (
                    "movil",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Teléfono inválido",
                                regex="^\\+?[\\d\\s\\-]{6,20}$",
                            )
                        ],
                        verbose_name="móvil",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="correo electrónico"
                    ),
                ),
                (
                    "direccion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="personas",
                        to="gestion.direccion",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="explotacion",
            name="titular",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="explotaciones_titular",
                to="gestion.persona",
            ),
        ),
        migrations.CreateModel(
            name="DiarioActividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(db_index=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("SIEMBRA", "Siembra"),
                            ("RIEGO", "Riego"),
                            ("ABONADO", "Abonado"),
                            ("TRATAMIENTO", "Tratamiento fitosanitario"),
                            ("COSECHA", "Cosecha"),
                            ("OTRO", "Otro"),
                        ],
                        default="OTRO",
                        max_length=30,
                        verbose_name="tipo actividad",
                    ),
                ),
                ("hora_inicio", models.TimeField(blank=True, null=True)),
                ("hora_fin", models.TimeField(blank=True, null=True)),
                (
                    "superficie_tratada_ha",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="superficie tratada (ha)",
                    ),
                ),
                (
                    "problema_fitosanitario",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        verbose_name="problema fitosanitario",
                    ),
                ),
                (
                    "producto_nombre",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        verbose_name="producto - nombre comercial",
                    ),
                ),
                (
                    "producto_numero_registro",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="nº registro"
                    ),
                ),
                (
                    "dosis",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="dosis",
                    ),
                ),
                (
                    "dosis_text",
                    models.CharField(
                        blank=True,
                        help_text="Formato libre si aplica",
                        max_length=100,
                        verbose_name="dosis (texto)",
                    ),
                ),
                (
                    "eficacia",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="eficacia"
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "insumos",
                    models.JSONField(
                        blank=True, null=True, verbose_name="insumos / composición"
                    ),
                ),
                ("datos_extra", models.JSONField(blank=True, null=True)),
                (
                    "estado_validacion",
                    models.CharField(blank=True, default="pendiente", max_length=30),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "documentos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="documentos_diario",
                        to="gestion.documentodat",
                    ),
                ),
                (
                    "equipo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actividades",
                        to="gestion.equipoaplicacion",
                    ),
                ),
                (
                    "explotacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diario_actividades",
                        to="gestion.explotacion",
                    ),
                ),
                (
                    "parcela",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diario_actividades",
                        to="gestion.parcela",
                    ),
                ),
                (
                    "aplicador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actividades_aplicadas",
                        to="gestion.persona",
                    ),
                ),
                (
                    "aprobado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aprobaciones_diario",
                        to="gestion.persona",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Asesor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_inscripcion_ropo",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Número de inscripción en el ROPO (si aplica)",
                        max_length=50,
                        verbose_name="nº inscripción ROPO",
                    ),
                ),
                (
                    "tipo_carnet",
                    models.CharField(
                        blank=True,
                        help_text="Tipo de carné (básico, cualificado, fumigador, piloto, ...)",
                        max_length=50,
                        verbose_name="tipo de carné",
                    ),
                ),
                (
                    "persona",
                    models.OneToOneField(
                        help_text="Persona física o jurídica asociada al asesor",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asesor_profile",
                        to="gestion.persona",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistroMovimientoProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(db_index=True)),
                ("producto", models.CharField(max_length=200, verbose_name="producto")),
                (
                    "cantidad_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="cantidad (kg)",
                    ),
                ),
                (
                    "numero_albaran",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="nº albarán / factura"
                    ),
                ),
                (
                    "numero_lote",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="nº de lote"
                    ),
                ),
                (
                    "cliente_nombre",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="cliente"
                    ),
                ),
                (
                    "cliente_nif",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="NIF cliente"
                    ),
                ),
                ("cliente_direccion", models.JSONField(blank=True, null=True)),
                (
                    "numero_rgseaa",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="nº RGSEAA"
                    ),
                ),
                (
                    "explotacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos_producto",
                        to="gestion.explotacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SemillaTratada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_siembra", models.DateField(db_index=True)),
                (
                    "cultivo",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="cultivo"
                    ),
                ),
                (
                    "superficie_sembrada_ha",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="superficie sembrada (ha)",
                    ),
                ),
                (
                    "cantidad_semilla_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="cantidad semilla (kg)",
                    ),
                ),
                (
                    "producto_fitosanitario",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        verbose_name="producto fitosanitario",
                    ),
                ),
                (
                    "numero_registro",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="nº registro"
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "explotacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semillas_tratadas",
                        to="gestion.explotacion",
                    ),
                ),
                (
                    "parcela",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="siembras",
                        to="gestion.parcela",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Titular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("apellidos", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("DNI", "DNI"),
                            ("NIE", "NIE"),
                            ("PASAPORTE", "Pasaporte"),
                        ],
                        max_length=20,
                    ),
                ),
                ("documento", models.CharField(max_length=20, unique=True)),
                (
                    "cif_explotacion",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("registro_explotacion", models.CharField(max_length=100)),
                (
                    "direccion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="titulares",
                        to="gestion.direccion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transportista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=250)),
                ("nif", models.CharField(blank=True, db_index=True, max_length=30)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "direccion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transportistas",
                        to="gestion.direccion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistroTransporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "referencia",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                (
                    "dat_numero",
                    models.CharField(
                        blank=True, db_index=True, max_length=150, null=True
                    ),
                ),
                ("fecha_transporte", models.DateTimeField(db_index=True)),
                ("tiempo_carga", models.DateTimeField(blank=True, null=True)),
                ("tiempo_descarga", models.DateTimeField(blank=True, null=True)),
                (
                    "cantidad",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("unidad", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "peso_bruto",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                (
                    "peso_neto",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                ("pallets", models.IntegerField(blank=True, null=True)),
                ("bultos", models.IntegerField(blank=True, null=True)),
                ("lotes", models.JSONField(blank=True, null=True)),
                ("temperatura_controlada", models.BooleanField(default=False)),
                (
                    "temp_registrada",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("ruta", models.JSONField(blank=True, null=True)),
                ("seguimiento_gps", models.JSONField(blank=True, null=True)),
                ("permisos", models.JSONField(blank=True, null=True)),
                (
                    "receptor_firma",
                    models.FileField(blank=True, null=True, upload_to="firmas/"),
                ),
                (
                    "estado",
                    models.CharField(blank=True, default="pendiente", max_length=40),
                ),
                (
                    "costo_transporte",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("datos_extra", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conductor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transportes_conducidos",
                        to="gestion.persona",
                    ),
                ),
                (
                    "destinatario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transportes_destino",
                        to="gestion.persona",
                    ),
                ),
                (
                    "documento_dat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros_operativos",
                        to="gestion.documentodat",
                    ),
                ),
                (
                    "documentos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="registros_transporte_relacionados",
                        to="gestion.documentodat",
                    ),
                ),
                (
                    "explotacion_origen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transportes_origen",
                        to="gestion.explotacion",
                    ),
                ),
                (
                    "persona_origen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transportes_origen_persona",
                        to="gestion.persona",
                    ),
                ),
                (
                    "transportista",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transportes",
                        to="gestion.transportista",
                    ),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros_transporte",
                        to="gestion.vehiculo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Destinatario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "tipo_documento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DNI", "DNI"),
                            ("NIE", "NIE"),
                            ("PASAPORTE", "Pasaporte"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("documento", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "direccion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="destinatarios",
                        to="gestion.direccion",
                    ),
                ),
                (
                    "transporte_asignado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="destinatarios_que_usan",
                        to="gestion.vehiculo",
                    ),
                ),
            ],
        ),
    ]
