# Generated by Django 5.2.8 on 2025-11-30 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_direccion_personal_vehiculo_explotacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explotacion',
            name='titular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='explotaciones_titular', to='gestion.titular'),
        ),
    ]
