# Generated by Django 5.2.9 on 2025-12-02 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0004_alter_registrotransporte_destinatario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diarioactividad",
            name="aplicador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actividades_aplicadas",
                to="gestion.personal",
            ),
        ),
    ]
